version: '3'
services:

    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: P@ssword112233
            POSTGRES_USER: admin
            POSTGRES_DB: blogs




# The `volumes` section should be defined **outside** the `services` block
volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/apps/postgres

networks:
    backend-network:
        driver: bridge