spring:
    application:
        name: posts-service
    config:
        import: optional:classpath:.env[.properties]
    datasource:
        password: P@ssword*123
        url: jdbc:postgresql://code4fun.id.vn:5432/blogs?currentSchema=blog_dbo2
        username: dev
    flyway:
        password: P@ssword*123
        url: jdbc:postgresql://code4fun.id.vn:5432/blogs?currentSchema=blog_dbo2
        user: dev
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
    kafka:
        bootstrap-servers:
            - http://code4fun.id.vn:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    mail:
        host: smtp.gmail.com
        username: translatorvamkv1@gmail.com
        password: lcyhfdfjdhahknmu
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
    servlet:
        multipart:
            max-file-size: 25MB
            max-request-size: 25MB
    profiles:
        active: local
    data:
        redis:
            host: code4fun.id.vn
            port: 6379
            database: 0
            password: tuanbeovn17
            username: default
#management:
#    endpoints:
#        web:
#            exposure:
#                include: health
#    otlp:
#        metrics:
#            export:
#                url: http://localhost:4318/v1/metrics
#                step: 3s
#        tracing:
#            endpoint: http://localhost:4318/v1/traces
#    tracing:
#        sampling:
#            probability: 1.0
# Email Sender
email:
    registration-confirmation:
        template: registration-confirmation.html
        subject: Registration Confirmation
        from: noreply@pezzie.com
        base-url: http://localhost:8080/user/api/v1/auth/regitrationConfirm?token=%s
    forgot-password-confirmation:
        template: forgot-password-template.html
        subject: Registration Confirmation
        from: noreply@pezzie.com
        base-url: http://localhost:8080/api/v1/auth/forgotPasswordConfirmation?token=%s

app:
    generate-categories: true

flywaypf:
    active: blog_dbo2

api:
    username: admin
    password: 123456

file:
    upload:
        url: http://localhost:8081

notifications:
    event:
        url: http://code4fun.id.vn:8090
jwt:
    expiryMinutes: 60
    expiryDay: 14
    accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
    refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
management:
    endpoint:
        health:
            show-details: always
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        configs:
            default:
                automaticTransitionFromOpenToHalfOpenEnabled: true
                failureRateThreshold: 50
                ignoreExceptions: com.myblogbackend.blog.exception.ExternalServiceException
                minimumNumberOfCalls: 4
                permittedNumberOfCallsInHalfOpenState: 3
                registerHealthIndicator: true
                slidingWindowSize: 6
                slidingWindowType: COUNT_BASED
                waitDurationInOpenState: PT30S
        instances:
            uploadMinioProxyCircuitBreaker:
                baseConfig: default
    retry:
        configs:
            default:
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2
                ignoreExceptions: com.myblogbackend.blog.exception.ExternalServiceException
                maxAttempts: 4
                waitDuration: 1000
        instances:
            uploadMinioProxyRetry:
                baseConfig: default

